jobs:
    include:
      - stage: test
        name: "LightWord Frontend"
        language: node_js
        node_js:
            - '13.8.0'
        cache:
            directories:
                - node_modules
        before_install:
            - cd LightWordFrontend
        install:
            - npm install
        script:
            - npm run build
    
      - stage: test
        name: "LightWord"
        language: bash
        services:
            - docker
        sudo: required
        addons:
            hosts:
              - api.shiroyk.moe
              - shiroyk.moe
        branches:
            only:
                - master
        script:
            - docker-compose up -d
        after_script:
            - curl -H "Content-Type:application/json" -X POST -d '{"test"}' http://api.shiroyk.moe/token
