jobs:
    include:
      - stage: test
        name: "LightWord Frontend"
        language: node_js
        node_js:
            - '13.8.0'
        cache:
            directories:
                - node_modules
        before_install:
            - cd Frontend
        install:
            - npm install
        script:
            - npm run build
    
      - stage: test
        name: "LightWord"
        language: bash
        services:
            - docker
        sudo: required
        branches:
            only:
                - master
        script:
            - docker-compose up -d
        after_script:
            - while [[ "$(curl -X POST -s -o /dev/null -w ''%{http_code}'' 'http://localhost/api/token')" != "401" ]]; do sleep 5; done && echo "Backend Ok"
