version: '3.4'
services:
    nginx:
        image: nginx:latest
        restart: always
        container_name: nginx
        depends_on:
            - backend
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./LightWordFrontend/dist:/usr/share/nginx/html
            - ./nginx/logs:/var/logs/nginx
        networks:
            - api_net
        ports:
            - 80:80
    db:
        image: mysql:5.6
        restart: always
        container_name: db
        environment: 
            MYSQL_ROOT_PASSWORD: guess123
            MYSQL_DATABASE: webdb
            MYSQL_USER: web
            MYSQL_PASSWORD: 123456
        volumes:
            - ./db/conf:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/logs:/var/log/mysql
            - ./db/webdb.sql:/docker-entrypoint-initdb.d/webdb.sql
        networks:
            - db_net
        ports:
            - 127.0.0.1:3306:3306
    backend:
        build:
            context: ./LightWordBackend
            dockerfile: Dockerfile
        image: backend:latest
        restart: always
        container_name: backend
        depends_on:
            - db
            - redis
        volumes:
            - ./LightWordBackend:/home/app/
        networks:
            - db_net
            - api_net
            - redis_net
        ports:
            - 127.0.0.1:5000:5000
    redis:
        image: redis:alpine
        restart: always
        container_name: redis
        networks:
            - redis_net
        ports:
            - 127.0.0.1:6379:6379

networks:
    db_net:
        driver: bridge
    api_net:
        driver: bridge
    redis_net:
        driver: bridge
